// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xroohcmewcogactmhrze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhyb29oY21ld2NvZ2FjdG1ocnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyOTM5MzYsImV4cCI6MjA3Mjg2OTkzNn0.sWcedqI9iKRlIDCWL4EurwwrUp8m85mek4tobJlz0eU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});